source 'https://rubygems.org'
ruby '2.1.2'
#ruby-gemset=railstutorial

gem 'rails', '4.1.4'
gem 'pg'

group :development, :test do
  gem 'spring-commands-rspec'
  gem 'rb-fsevent', require: false
  gem 'rspec-rails'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'guard-pow'
  gem 'guard-livereload'
end

group :test do
  gem 'selenium-webdriver'
  gem 'capybara'
end

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'pry-rails',  group: :development

group :production do
  gem 'rails_12factor'
end
